### ISSUE TITLE
 Could not find or load main class net.shibboleth.tool.xmlsectool.XMLSecTool

### ISSUE THREAD

**Issue by MicheleMallia** [clarin-eric/SAML-metadata-checker#1]
I can't proceed to validation because:

Error: Could not find or load main class net.shibboleth.tool.xmlsectool.XMLSecTool
Caused by: java.lang.ClassNotFoundException: net.shibboleth.tool.xmlsectool.XMLSecTool

This is the problem:

"$JAVACMD" '-Xmx256m' '-classpath' "$LOCALCLASSPATH" $JVMOPTS '-Dnet.shibboleth.tool.xmlsectool.XMLSecTool.home='"$LOCATION" 'net.shibboleth.tool.xmlsectool.XMLSecTool' "$@"

xmlsectool-2.0.0.jar in under /lib folder.

I use GitBash under Windows 11.

**Comment by andmor-** [comment]
Difficult to tell. Can you run `xmlsectool.sh` writing `set -x` on line 7 of the script and provide the output? I am mainly interested on the values of `$LOCALCLASSPATH` and `$LOCATION` so you can also just echo them

**Comment by MicheleMallia** [comment]
The problem was a character at the line 45:

LOCALCLASSPATH="$LOCALCLASSPATH;$i"

Because Windows can't digest well this char, I've used chat gpt to find this bug.

This is the code for windows 11:

```
#! /bin/bash

#
# See the Javadoc for the XMLSecTool main class for documentation
# of non-zero exit codes.
#

declare LOCATION
declare COMMAND
declare JAVACMD
declare LOCALCLASSPATH
declare LIBDIR

LOCATION=$0
LOCATION=${LOCATION%/*}

if [ -z "$JAVA_HOME" ] ; then
  echo "ERROR: JAVA_HOME environment variable is not set."
  exit 8
else
  if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
    # IBM's JDK on AIX uses strange locations for the executables
    JAVACMD=$JAVA_HOME/jre/sh/java
  else
    JAVACMD=$JAVA_HOME/bin/java
  fi
fi

if [ ! -x "$JAVACMD" ] ; then
  echo "Error: JAVA_HOME is not defined correctly."
  echo "  We cannot execute $JAVACMD"
  exit 9
fi

LOCALCLASSPATH="$JAVA_HOME/lib/tools.jar;$JAVA_HOME/lib/classes.zip"

# add in the dependency .jar files from the lib directory
LIBDIR="$LOCATION/lib"
LIBS="$LIBDIR"/*.jar
for i in $LIBS
do
    # if the directory is empty, then it will return the input string
    # this is stupid, so case for it
    if [ "$i" != "${LIBS}" ] ; then
        LOCALCLASSPATH="$LOCALCLASSPATH;$i"
    fi
done

# Print LOCALCLASSPATH for debugging
echo "LOCALCLASSPATH is: $LOCALCLASSPATH"

"$JAVACMD" '-classpath' "$LOCALCLASSPATH" $JVMOPTS '-Dnet.shibboleth.tool.xmlsectool.XMLSecTool.home='"$LOCATION" 'net.shibboleth.tool.xmlsectool.XMLSecTool' "$@"

```

**Comment by andmor-** [comment]
Thanks. I think that will also work in bash so I will update our code when I find the time to test it. Fell free to submit a PR meanwhile.

**Comment by MicheleMallia** [comment]
Done.
